openapi: 3.1.0
info:
  title: prefectures
  version: '1.0'
  summary: 都道府県一覧
servers:
  - url: 'https://opendata.resas-portal.go.jp'
paths:
  /api/v1/prefectures:
    get:
      summary: prefectures
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type:
                      - string
                      - 'null'
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        prefCode:
                          type: number
                        prefName:
                          type: string
              examples:
                example-1:
                  value:
                    message: message
                    result:
                      - prefCode: 1
                        prefName: 北海道
                      - prefCode: 2
                        prefName: 青森県
                      - prefCode: 3
                        prefName: 岩手県
                      - prefCode: 4
                        prefName: 宮城県
                      - prefCode: 5
                        prefName: 秋田県
                      - prefCode: 6
                        prefName: 山形県
                      - prefCode: 7
                        prefName: 福島県
                      - prefCode: 8
                        prefName: 茨城県
                      - prefCode: 9
                        prefName: 栃木県
                      - prefCode: 10
                        prefName: 群馬県
                      - prefCode: 11
                        prefName: 埼玉県
                      - prefCode: 12
                        prefName: 千葉県
                      - prefCode: 13
                        prefName: 東京都
                      - prefCode: 14
                        prefName: 神奈川県
                      - prefCode: 15
                        prefName: 新潟県
                      - prefCode: 16
                        prefName: 富山県
                      - prefCode: 17
                        prefName: 石川県
                      - prefCode: 18
                        prefName: 福井県
                      - prefCode: 19
                        prefName: 山梨県
                      - prefCode: 20
                        prefName: 長野県
                      - prefCode: 21
                        prefName: 岐阜県
                      - prefCode: 22
                        prefName: 静岡県
                      - prefCode: 23
                        prefName: 愛知県
                      - prefCode: 24
                        prefName: 三重県
                      - prefCode: 25
                        prefName: 滋賀県
                      - prefCode: 26
                        prefName: 京都府
                      - prefCode: 27
                        prefName: 大阪府
                      - prefCode: 28
                        prefName: 兵庫県
                      - prefCode: 29
                        prefName: 奈良県
                      - prefCode: 30
                        prefName: 和歌山県
                      - prefCode: 31
                        prefName: 鳥取県
                      - prefCode: 32
                        prefName: 島根県
                      - prefCode: 33
                        prefName: 岡山県
                      - prefCode: 34
                        prefName: 広島県
                      - prefCode: 35
                        prefName: 山口県
                      - prefCode: 36
                        prefName: 徳島県
                      - prefCode: 37
                        prefName: 香川県
                      - prefCode: 38
                        prefName: 愛媛県
                      - prefCode: 39
                        prefName: 高知県
                      - prefCode: 40
                        prefName: 福岡県
                      - prefCode: 41
                        prefName: 佐賀県
                      - prefCode: 42
                        prefName: 長崎県
                      - prefCode: 43
                        prefName: 熊本県
                      - prefCode: 44
                        prefName: 大分県
                      - prefCode: 45
                        prefName: 宮崎県
                      - prefCode: 46
                        prefName: 鹿児島県
                      - prefCode: 47
                        prefName: 沖縄県
      operationId: get-api-v1-prefectures
      description: 都道府県情報を取得
      security:
        - API Key - 1: []
      parameters: []
  /api/v1/population/composition/perYear:
    get:
      summary: population composition
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type:
                      - string
                      - 'null'
                  result:
                    type: object
                    properties:
                      boundaryYear:
                        type: number
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            label:
                              type: string
                            data:
                              type: array
                              items:
                                type: object
                                properties:
                                  year:
                                    type: number
                                  label:
                                    type: number
              examples:
                example-1:
                  value:
                    message: string
                    result:
                      boundaryYear: 2015
                      data:
                        - label: 総人口
                          data:
                            - year: 1980
                              value: 12817
                            - year: 1985
                              value: 12707
      operationId: get-api-v1-population-composition-perYear
      description: |
        地域単位、年単位の年齢構成のデータを返します。
      security:
        - API Key - 1: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                prefCode:
                  description: 都道府県コード
                  type: number
                cityCode:
                  type:
                    - string
                    - number
                  description: 市区町村コード(すべての場合は-を送る)
                addArea:
                  type: string
                  description: 追加エリアコード（他地域と合算した値を取得する際に使用するパラメータ）
              required:
                - prefCode
                - cityCode
            examples:
              example-1:
                value:
                  prefCode: 1
                  cityCode: '-'
        description: 'https://opendata.resas-portal.go.jp/docs/api/v1/population/composition/perYear.html'
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
