openapi: 3.0.2
info:
  title: prefectures
  version: '1.0'
  description: ''
  contact:
    name: Resas
    url: 'https://opendata.resas-portal.go.jp/'
  termsOfService: 'https://opendata.resas-portal.go.jp/'
  license: {}
servers:
  - url: 'https://opendata.resas-portal.go.jp'
paths:
  /api/v1/prefectures:
    get:
      summary: prefectures
      tags: []
      operationId: get-api-v1-prefectures
      description: 都道府県情報を取得
      security: []
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/prefectures'
  /api/v1/population/composition/perYear:
    get:
      summary: population composition
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/populationComposition'
      operationId: get-api-v1-population-composition-perYear
      description: |
        地域単位、年単位の年齢構成のデータを返します。
      security: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/populationQuery'
components:
  schemas:
    prefectures:
      title: prefectures
      type: array
      items:
        type: object
        properties:
          prefCode:
            type: string
          prefName:
            type: string
        required:
          - prefCode
          - prefName
    population:
      title: populationResult
      type: object
      properties:
        boundaryYear:
          type: number
        data:
          type: array
          items:
            type: object
            properties:
              year:
                type: number
              value:
                type: number
            required:
              - year
              - value
      required:
        - boundaryYear
        - data
    populationQuery:
      title: populationQuery
      type: object
      properties:
        prefCode:
          type: number
        cityCode:
          type: string
        addArea:
          type: string
      required:
        - prefCode
        - cityCode
  securitySchemes: {}
  responses:
    prefectures:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                nullable: true
              result:
                type: array
                items:
                  $ref: '#/components/schemas/prefectures'
        application/xml:
          schema:
            type: object
            properties: {}
    populationComposition:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                nullable: true
              result:
                type: array
                items:
                  $ref: '#/components/schemas/population'
            required:
              - message
  parameters: {}
