name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  admin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          awk -F "=" '{if( $1 ~ "NODE_VERSION" ) print $0}' ./../.env >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore yarn cache
        uses: actions/cache@v2
        with:
          path: admin/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run check-all
        run: yarn check-all
